podspec: LASwift.podspec

github_url: https://github.com/AlexanderTar/LASwift/

swift_version: 5.0

min_acl: public
skip_undocumented: true
hide_documentation_coverage: true
clean: true

use_safe_filenames: true
