# podspec: LASwift.podspec

author: Alexander Taraymovich
github_url: https://github.com/AlexanderTar/LASwift/

module: LASwift
swift_build_tool: spm
build_tool_arguments:
  - -Xswiftc
  - -swift-version
  - -Xswiftc
  - "5"

min_acl: public
skip_undocumented: true
hide_documentation_coverage: true
clean: true

use_safe_filenames: true
